= arithmetic-server

This is a tiny demonstration of arithmetic, used in a MicroServices Architecture
course that I teach (https://learningtree.com/1850).
Spring Boot provides the ability to build tiny services like this, thanks to
the Apache Tomcat project's "embeddable Tomcat".

This style of project would be quite suitable for use as a MicroService, given
other infrastructure around it (Docker, Kubernetes, ...).

== Security

Note that as presently configured, if you run this as-is, your server will be open to access from the world!
Be sure there are no insecure bits of code for bad actors to exploit.
And don't publicize it widely, lest you get hit with denial-of-service attacks
(consider rate-limiting in pf(8) or whatever firewall you use).
To change this, whack out the line with 0.0.0.0 in application-properties.

== HTTP or HTTPS?

The server can be configured to uses either plain HTTP or TSL (https) on port 8910, the latter with a self-signed certificate.
In either case there are issues around poking at it with a browser just to be sure it's running:

* `http`:
If you run it on the same machine as a real web server that is configured correctly (using HSTS),
you will not be able to visit it with any browser.
It will work with `telnet hostname 8910` with `GET / http/1.0` (use `nc` if your system has deleted telnet).
And it will do its main job, working as a MicroService accessed via REST.

* `https`:
This will NOT work with Chrome!
With Firefox, you can visit https://hostname:8910/help and accept the Danger warnings.
With PostMan, which you need in order to submit the POST requests,
you need to go File->Settings-General->SSL Certificate Verification->Off
(Remember to turn it back on when doing serious work!)

== Usage

To start it, you should only need to invoke the 'runserver' script.

To get help, `GET` the `/help` URL.

To use it, `POST` to `/arithmetic` with `Content-type: application/json` and a JSON body like

	{ "num1": 67, "num2", 25, "operation", "-" }

The op can be any of

	add subtract multiply divide modulus
	+ - * / %

The return value is a formatted string, alas, becuase this service has to be compatible with
one that was set up by to favor simplicity over generality. IRL it would return a numeric value
that would be formatted into a (language-localized) string for presentation.

== Acknowledgement

I think I started with the below link, or a how-to that put the same elements together.
At any rate, it's an easy way for you to start your own project:

	git clone https://github.com/spring-guides/gs-spring-boot
